---
- name: Set up Ubuntu 24.04
  hosts: localhost
  become: true
  gather_facts: false

  vars_files:
    - defaults/main.yml

  pre_tasks:
    - name: Perform a dist-upgrade
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
    - name: Import utils task
      ansible.builtin.import_tasks: tasks/utils.yml
      tags: ["utils"]

  roles:
    - role: docker
      vars:
        docker_user: "{{ user }}"
      tags: ["docker"]
    - role: devops_tools
      tags: ["devops_tools"]

  tasks:
    - name: Import ZSH task
      ansible.builtin.import_tasks: tasks/zsh.yml
      tags: ["zsh"]
    - name: Import customizations task
      ansible.builtin.import_tasks: tasks/customizations.yml
      tags: ["customizations"]

  post_tasks:
    - name: Remove obsolete dependencies
      ansible.builtin.apt:
        autoremove: true
