---
- hosts: localhost
  connection: local
  become: true

  vars_files:
    - default.config.yml

  tasks:
  - name: Ensure Ansible downloads directory exists
    file:
      path: "{{ downloads_dir }}"
      state: directory

  - import_tasks: tasks/az-cli.yml
      tags: ['az-cli']