---
- hosts: localhost
  become: true

  vars_files:
    - default.config.yml

  tasks:
  - import_tasks: tasks/tools.yml
    tags: ['tools']
  - import_tasks: tasks/azure-cli.yml
    tags: ['azure-cli']
  - import_tasks: tasks/terraform.yml
    tags: ['terraform']