---
- name: Set up Ubuntu 22.04
  hosts: localhost
  become: true
  gather_facts: false

  vars_files:
    - defaults/main.yml

  pre_tasks:
    - name: Run apt dist-upgrade if the last one was more than 3600 seconds ago
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
        upgrade: dist
      tags: ["always"]
      notify:
        - Remove obsolete apt dependencies

  roles:
    - role: docker
      vars:
        docker_user: "{{ user }}"
      tags: ["docker"]
    - role: devops_tools
      tags: ["devops_tools"]

  tasks:
    - name: Import utils task
      ansible.builtin.import_tasks: tasks/utils.yml
      tags: ["utils"]
    - name: Import ZSH task
      ansible.builtin.import_tasks: tasks/zsh.yml
      tags: ["zsh"]
    - name: Import customizations task
      ansible.builtin.import_tasks: tasks/customizations.yml
      tags: ["customizations"]
