---
- hosts: localhost
  become: true

  vars_files:
    - defaults/main.yml

  pre_tasks:
    - name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
      apt:
        update_cache: yes
        cache_valid_time: 3600
      tags: ["always"]

  roles:
    - role: docker
      vars:
        docker_user: "{{ user }}"
      tags: ["docker"]

  tasks:
    - import_tasks: tasks/customizations.yml
      tags: ["customizations"]
    - import_tasks: tasks/tools.yml
      tags: ["tools"]
    - import_tasks: tasks/azure-cli.yml
      tags: ["azure-cli"]
    - import_tasks: tasks/helm.yml
      tags: ["helm"]
    - import_tasks: tasks/kubectl.yml
      tags: ["kubectl"]
    - import_tasks: tasks/kubens.yml
      tags: ["kubens"]
    - import_tasks: tasks/kubectx.yml
      tags: ["kubectx"]
    - import_tasks: tasks/stern.yml
      tags: ["stern"]
    - import_tasks: tasks/terraform.yml
      tags: ["terraform"]
    - import_tasks: tasks/terraform-docs.yml
      tags: ["terraform"]
    - import_tasks: tasks/terragrunt.yml
      tags: ["terragrunt"]
    - import_tasks: tasks/zsh.yml
      tags: ["zsh"]
