---
- name: Set up Ubuntu 24.04
  hosts: localhost
  become: true
  gather_facts: false

  pre_tasks:
    - name: Perform a dist-upgrade
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist

  roles:
    - role: utils
      tags: ["utils"]
    - role: zsh
      tags: ["zsh"]
    - role: docker
      vars:
        docker_user: "{{ user }}"
      tags: ["docker"]
    - role: devops_tools
      tags: ["devops_tools"]
    - role: customizations
      tags: ["customizations"]

  post_tasks:
    - name: Remove obsolete dependencies
      ansible.builtin.apt:
        autoremove: true
