---
- hosts: localhost
  become: true
  gather_facts: false

  vars_files:
    - defaults/main.yml

  pre_tasks:
    - name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
      apt:
        update_cache: yes
        cache_valid_time: 3600
      tags: ["always"]

  roles:
    - role: roles/docker
      vars:
        docker_user: "{{ user }}"
      tags: ["docker"]

  tasks:
    - import_tasks: tasks/utils.yml
      tags: ["utils"]
    - import_tasks: tasks/zsh.yml
      tags: ["zsh"]
    - import_tasks: tasks/devops-tools.yml
      tags: ["devops-tools"]
    - import_tasks: tasks/customizations.yml
      tags: ["customizations"]
