---
docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin
docker_apt_gpg_key: https://download.docker.com/linux/ubuntu/gpg
docker_apt_repo_url: https://download.docker.com/linux/ubuntu
docker_dependencies:
  - ca-certificates
  - gnupg
docker_install_sdk_for_python: true
docker_sdk_for_python_packages:
  - python3-docker
