---
- name: Install azure-cli
  block:
  - name: Install required system packages
    apt:
      name: "{{ item }}"
      state: latest
      update_cache: yes
    loop:
    - ca-certificates
    - curl
    - apt-transport-https
    - lsb-release
    - gnupg

  - name: Add Microsoft GPG key to apt
    apt_key:
      url: https://packages.microsoft.com/keys/microsoft.asc
      state: present

  - name: Add Microsoft repository
    apt_repository:
      repo: deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ {{ distrib_codename }} main
      state: present

  - name: Update apt and install azure-cli
    apt:
      name: azure-cli
      state: latest
      update_cache: yes