- name: Copy Bash custom aliases
  ansible.builtin.copy:
    src: "files/.aliases"
    dest: "{{ homedir }}/.bash_aliases"
    remote_src: true
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0664

- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"
    use: systemd
