- name: Copy Bash custom aliases
  ansible.builtin.copy:
    src: "dotfiles/.aliases"
    dest: "{{ homedir }}/.bash_aliases"
    remote_src: true
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0664"

- name: Tmux config
  become: false
  become_user: "{{ user }}"
  # noqa: latest
  block:
    - name: Install tmux plugin manager
      # noqa: latest
      ansible.builtin.git:
        repo: https://github.com/tmux-plugins/tpm
        dest: "/home/{{ user }}/.tmux/plugins/tpm"
    - name: Install catppuccin theme
      # noqa: latest
      ansible.builtin.git:
        repo: https://github.com/catppuccin/tmux
        dest: "/home/{{ user }}/.tmux/plugins/catppuccin"
    - name: Copy .tmux.conf file
      ansible.builtin.copy:
        src: "dotfiles/.tmux.conf"
        dest: "{{ homedir }}"
        remote_src: true
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0664"

- name: Git config
  become: false
  become_user: "{{ user }}"
  block:
    - name: Set git username
      community.general.git_config:
        name: user.name
        scope: global
        value: "{{ full_name }}"

    - name: Set git email address
      community.general.git_config:
        name: user.email
        scope: global
        value: "{{ email }}"

    - name: Enable caching of git credentials
      community.general.git_config:
        name: credential.helper
        scope: global
        value: store

    - name: Set git default pull policy to merge
      community.general.git_config:
        name: pull.rebase
        scope: global
        value: false

    - name: Copy .gitalias file
      ansible.builtin.copy:
        src: "dotfiles/.gitalias"
        dest: "{{ homedir }}"
        remote_src: true
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0664"

    - name: Include .gitalias filepath
      community.general.git_config:
        name: include.path
        scope: global
        value: "{{ homedir }}/.gitalias"
