- name: Copy Bash custom aliases
  ansible.builtin.copy:
    src: "dotfiles/.aliases"
    dest: "{{ homedir }}/.bash_aliases"
    remote_src: true
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0664"

- name: Git preferences
  become: false
  become_user: "{{ user }}"
  block:
    - name: Set git username
      community.general.git_config:
        name: user.name
        scope: global
        value: "{{ full_name }}"

    - name: Set git email address
      community.general.git_config:
        name: user.email
        scope: global
        value: "{{ email }}"

    - name: Enable caching of git credentials
      community.general.git_config:
        name: credential.helper
        scope: global
        value: store

    - name: Set git default pull policy to merge
      community.general.git_config:
        name: pull.rebase
        scope: global
        value: false

    - name: Copy .gitalias file
      ansible.builtin.copy:
        src: "dotfiles/.gitalias"
        dest: "{{ homedir }}"
        remote_src: true
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0664"

    - name: Include .gitalias filepath
      community.general.git_config:
        name: include.path
        scope: global
        value: "{{ homedir }}/.gitalias"
