- name: Copy .bash_aliases
  copy:
    src: "files/.bash_aliases"
    dest: "{{ homedir }}/.bash_aliases"
    remote_src: true
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0664

- name: Set hostname
  hostname:
    name: "{{ hostname }}"
    use: systemd
