- name: Copy Bash custom aliases
  ansible.builtin.copy:
    src: "dotfiles/.aliases"
    dest: "{{ homedir }}/.bash_aliases"
    remote_src: true
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0664"

- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"
    use: systemd

- name: Set git username
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ full_name }}"
  become: false
  become_user: "{{ user }}"

- name: Set git email address
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ email }}"
  become: false
  become_user: "{{ user }}"

- name: Enable caching of git credentials
  community.general.git_config:
    name: credential.helper
    scope: global
    value: store
  become: false
  become_user: "{{ user }}"

- name: Set git default pull policy to merge
  community.general.git_config:
    name: pull.rebase
    scope: global
    value: false
  become: false
  become_user: "{{ user }}"
