---
- name: Install DevOps tools
  community.general.homebrew:
    name: "{{ devops_tools_packages }}"
    state: present
    path: "{{ homebrew_prefix }}/bin"
  become: false
  become_user: "{{ user }}"
