---
- name: Download Helm
  unarchive:
    src: "https://get.helm.sh/helm-v{{ helm_version }}-linux-amd64.tar.gz"
    dest: "{{ download_dir }}"
    remote_src: true
    mode: 0755
  register: helm_download

- name: Copy Helm binary to its path
  copy:
    src: "{{ download_dir }}/linux-amd64/helm"
    dest: "{{ bin_path }}"
    remote_src: true
    mode: 0775
  when: helm_download is changed
