---
- name: Download kubectl
  ansible.builtin.get_url:
    url: "https://storage.googleapis.com/kubernetes-release/release/v{{ kubectl_version }}/bin/linux/amd64/kubectl"
    dest: "{{ download_dir }}/kubectl"

- name: Copy kubectl binary to its path
  ansible.builtin.copy:
    src: "{{ download_dir }}/kubectl"
    dest: "{{ bin_path }}"
    remote_src: true
    mode: 0775
