---
- name: Download kubectl
  get_url:
    url: "https://dl.k8s.io/release/v{{ kubectl_version }}/bin/linux/amd64/kubectl"
    dest: "{{ download_dir }}/kubectl"
    checksum: "{{ kubectl_checksum }}"

- name: Copy kubectl binary to its path
  copy:
    src: "{{ download_dir }}/kubectl"
    dest: "{{ kubectl_bin_path }}"
    remote_src: true
    mode: 0775
