---
- name: Download Stern
  get_url:
    url: "https://github.com/wercker/stern/releases/download/{{ stern_version }}/stern_linux_amd64"
    dest: "{{ download_dir }}/stern_linux_amd64"

- name: Copy Stern binary to its path
  copy:
    src: "{{ download_dir }}/stern_linux_amd64"
    dest: "{{ stern_bin_path }}"
    remote_src: true
    mode: 0775
