---
- name: Download Terraform
  unarchive:
    src: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
    dest: "{{ download_dir }}"
    remote_src: true
    mode: 0755
  register: terraform_download

- name: Copy Terraform binary to its path
  copy:
    src: "{{ download_dir }}/terraform"
    dest: "{{ terraform_bin_path }}"
    remote_src: true
    mode: 0775
  when: terraform_download is changed
