---
- name: Download Terragrunt
  get_url:
    url: "https://github.com/gruntwork-io/terragrunt/releases/download/v{{ terragrunt_version }}/terragrunt_linux_amd64"
    dest: "{{ download_dir }}/terragrunt_linux_amd64"

- name: Copy Terragrunt binary to its path
  copy:
    src: "{{ download_dir }}/terragrunt_linux_amd64"
    dest: "{{ terragrunt_bin_path }}"
    remote_src: true
    mode: 0775
