---
- name: Install tools
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
  loop:
    - jq
    - unzip
    - tree
    - git
    - htop
    - wget
    - curl
    - tilix
    - shellcheck
    - neofetch
