---
- name: Install utils
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - git
    - htop
    - jq
    - pipx
    - shellcheck
    - tmux
    - tree
    - unzip
    - wget

- name: Ensure pipx is added to the PATH
  ansible.builtin.command: |
    pipx ensurepath
  become: false
  become_user: "{{ user }}"
  register: pipx_result
  changed_when: pipx_result.rc != 0
