---
- name: Install utils
  community.general.homebrew:
    name:
      - curl
      - git
      - htop
      - jq
      - parallel
      - shellcheck
      - tmux
      - tree
      - unzip
      - wget
      - yq
    state: present
    path: "{{ homebrew_prefix }}/bin"
  become: false
  become_user: "{{ user }}"
