---
- name: Install utils
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
  loop:
    - curl
    - git
    - htop
    - jq
    - neofetch
    - shellcheck
    - tree
    - unzip
    - wget
