---
- name: Set up ZSH
  block:
    - name: Install ZSH
      ansible.builtin.apt:
        name: zsh
        state: present

    - name: Set ZSH as the default shell
      ansible.builtin.user:
        name: "{{ user }}"
        shell: /usr/bin/zsh

- name: Set up tmux
  block:
    - name: Install tmux
      ansible.builtin.apt:
        name: tmux
        state: present

    - name: Clone tmux plugin manager repo
      # noqa: latest
      ansible.builtin.git:
        repo: https://github.com/tmux-plugins/tpm
        dest: "/home/{{ user }}/.tmux/plugins/tpm"

- name: Set up oh-my-zsh
  block:
    - name: Check if .oh-my-zsh directory exists
      ansible.builtin.stat:
        path: /home/{{ user }}/.oh-my-zsh
      register: oh_my_zsh_dir

    - name: Download oh-my-zsh install script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: "{{ download_dir }}/ohmyzsh_install.sh"
        mode: "0555"
      when: not oh_my_zsh_dir.stat.exists

    - name: Install oh-my-zsh
      ansible.builtin.script: |
        "{{ download_dir }}/ohmyzsh_install.sh"
      become: false
      become_user: "{{ user }}"
      register: oh_my_zsh_output
      changed_when: "'folder already exists' not in oh_my_zsh_output.stdout"
      when: not oh_my_zsh_dir.stat.exists
