---
devops_tools_python:
  packages:
    - azure-cli
    - poetry
    - yamllint
devops_tools_versions:
  helm: 3.14.0
  kubectl: 1.29.1
  kubens: 0.9.4
  kubectx: 0.9.4
  stern: 1.22.0
  terraform: 1.7.3
  terraform_docs: 0.16.0
