---
devops_tools_python_packages:
  - ansible-lint
  - azure-cli
  - poetry
  - yamllint
devops_tools_versions:
  hadolint: 2.12.1
  kubectl: 1.29.1
  kubens: 0.9.4
  kubectx: 0.9.4
  stern: 1.22.0
  terraform_docs: 0.16.0
