---
- name: Ensure old versions of Docker are not installed
  ansible.builtin.package:
    name:
      - docker.io
      - docker-compose
      - docker-compose-v2
      - docker-doc
      - podman-docker
      - containerd
      - runc
    state: absent

- name: Install Docker dependencies
  ansible.builtin.apt:
    name: "{{ docker_dependencies }}"
    state: present

- name: Gather distribution codename
  ansible.builtin.setup:
    filter:
      - ansible_distribution_release

- name: Add Docker repository
  ansible.builtin.deb822_repository:
    name: docker
    state: present
    uris: ["{{ docker_apt_repo_url }}"]
    suites: ["{{ ansible_distribution_release }}"]
    components: [stable]
    architectures: [amd64]
    signed_by: "{{ docker_apt_gpg_key }}"
    enabled: true
  notify:
    - Update apt cache

- name: Ensure handlers are notified now for the Docker repository to be available
  ansible.builtin.meta: flush_handlers

- name: Install Docker
  ansible.builtin.apt:
    name: "{{ docker_packages }}"
    state: present
  notify:
    - Enable Docker
    - Restart Docker

- name: Ensure handlers are notified now for the Docker service changes to take effect
  ansible.builtin.meta: flush_handlers

- name: Add user to the docker group
  ansible.builtin.user:
    name: "{{ docker_user }}"
    groups: docker
    append: true
  when: docker_user is defined

- name: Install Docker SDK for Python
  ansible.builtin.apt:
    name: "{{ docker_sdk_for_python_packages }}"
    state: present
  when: docker_install_sdk_for_python | bool
