---
- name: Ensure old versions of Docker are not installed
  ansible.builtin.package:
    name:
      - docker
      - docker-engine
    state: absent

- name: Install dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ docker_dependencies }}"

- name: Add Docker GPG key to apt
  ansible.builtin.get_url:
    url: "{{ docker_apt_gpg_key }}"
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: "0775"
    force: true

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "{{ docker_deb_repository }}"
    state: present

- name: Install Docker
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ docker_packages }}"
  notify:
    - Enable Docker
    - Restart Docker

- name: Ensure handlers are notified now for the Docker service changes to take effect
  ansible.builtin.meta: flush_handlers

- name: Add user to the docker group
  ansible.builtin.user:
    name: "{{ docker_user }}"
    groups: docker
    append: true
  when: docker_user is defined

- name: Install dependencies for Docker SDK for Python
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ docker_sdk_for_python_dependencies }}"
  when: docker_install_sdk_for_python | bool

- name: Install Docker SDK for Python
  ansible.builtin.pip:
    name: docker
  when: docker_install_sdk_for_python | bool
